Install guide
ENERZAi/OptimaV2-Docs pull request #2
Opened 2023-02-12 14:34 UTC by jwkim98

Documented install guide

* We need to add installation guide via pypi!

2023-02-28 02:59 UTC, jaeyoon-enerzai requested changes

2023-02-28 02:59 UTC, jaeyoon-enerzai commented on docs/guide/install.md
> +    These docker images should have complete setup for using and testing OptimaV2 and OptimaV2 runtime on cpu.
snpe convert를 위해서는 (docker out of docker를 위해)

docker run -v /var/run/docker.sock:/var/run/docker.sock 을 추가해야한다고 넣어주세요

2023-02-28 02:59 UTC, jaeyoon-enerzai commented on docs/guide/install.md
>      This process will prompt you to enter github token or username if you don't have access privilege to torch2nx library. In this case, contact OptimaV2 team. We will grant you permissions for insta
pypi server로 넣으면서 아마 github token을 요구하진 않을 것입니다

2023-03-02 07:49 UTC, jwkim98 commented on docs/guide/install.md
> +    These docker images should have complete setup for using and testing OptimaV2 and OptimaV2 runtime on cpu.
Sure

2023-03-06 03:26 UTC, beom-k approved these changes

2023-03-07 08:38 UTC, jaeyoon-enerzai approved these changes

2023-03-07 08:38 UTC, jaeyoon-enerzai commented on docs/guide/install.md
> +    **Step 2:** Install torch-mlir (This dependency is going to be deprecated will be removed in future releases)
grammar check

2023-03-08 02:27 UTC, jinhwan-enerzai commented on docs/guide/install.md
> +    | Testing          | `doctest`              | `-DENABLE_TESTING=ON` | Disabled on Release build                                     |
apt 기준이 아니라 runtime에 들어있는 install 스크립트 기준입니다.

`python -m install doctest` 이런 식으로 입력해서 설치합니다.

2023-03-08 02:28 UTC, jinhwan-enerzai approved these changes

2023-03-08 02:28 UTC, merged