about docs added
ENERZAi/OptimaV2-Docs pull request #4
Opened 2023-02-26 03:39 UTC by jaeyoon-enerzai

2023-03-02 08:11 UTC, jwkim98 approved these changes

2023-03-02 08:11 UTC, jwkim98 commented on docs/about.md
> +- It covers all work to be done in graph level
Removing 'It' might make it look better

2023-03-02 08:11 UTC, jwkim98 commented on docs/about.md
> +### (Desired) Features
I think we need to provide information about what is possible right now, and what can be added in the future

2023-03-06 03:13 UTC, beom-k approved these changes

2023-03-06 03:21 UTC, seongju-enerzai approved these changes

2023-03-07 04:13 UTC, jaeyoon-enerzai commented on docs/about.md
> +### (Desired) Features
기본적으로 현재로써는(step1) 모두 desired feature라고 보는 게 낫겠습니다 -> Desired feature라고 바꾸겠습니다

2023-03-07 04:55 UTC, jinhwan-enerzai approved these changes

2023-03-07 08:14 UTC, jwkim98 commented
```python
# Import Manager from optima_v2
from optima_v2.manager import Manager
from optima_v2.devices import DeviceEnum

# ... 
manager_instance = Manager()
manager_instance.optimize(
    "MediapipeNet",
    [
        DeviceEnum.DEVICE_KIND_HEXAGON,
        DeviceEnum.DEVICE_KIND_X64,
    ],
    "~/models/mediapipe/mediapipe.gpickle",
    "~/outputs/",
    "~/models/mediapipe/mediapipe_allocation.json",
    representative_data,
)
```

위 예시에서 optima_v2.manager 가 optima_v2.manager.manager로 수정되어야 합니다

2023-03-07 08:23 UTC, jwkim98 commented
Docs가 전반적으로 코드의 전체 모습을 한 눈에 보기 어려워서 전체 코드를 넣어서 한번 쯤 다시 정리해주면 더 보기 편할 듯 합니다

2023-03-07 08:24 UTC, jwkim98 requested changes

2023-03-07 08:24 UTC, jwkim98 commented on docs/about.md
> +If you have any issue and need an assistance, then please feel free to upload your requirement in http://192.168.0.80:8080/
이거 192로 시작하는 링크 말고 포트포워딩된 링크 (remote.enerzai.com:18080)으로 바꾸는게 어떨까요?

2023-03-07 08:37 UTC, jwkim98 commented
install_guide리뷰 & 머지 후 업데이트 받으셔서 새로운 template 적용이 필요합니다 (템플릿이 material로 바뀌었습니다)

2023-03-07 08:41 UTC, jaeyoon-enerzai commented on docs/about.md
> +If you have any issue and need an assistance, then please feel free to upload your requirement in http://192.168.0.80:8080/
포트포워딩을 했군요 계속 192로 들어가고 있었어요
네 반영했습니다

2023-03-08 09:27 UTC, seongju-enerzai commented on docs/about.md
> +    - It extends the scope of AI researchers by supporting complex operations that are not compatible with MHLO, TOSA, and other similar technologies."
13번 줄 마지막 쌍따옴표 하나가 잘못 들어가 있는 것 같습니다.

2023-03-08 09:27 UTC, seongju-enerzai commented on docs/about.md
> +    - our first target is to surpass tensorflow(tf-lite), and we will aim to target tvm based compilers
17번 줄 시작을 다른 부분과 같이 대문자로 부탁드립니다.

2023-03-08 09:27 UTC, seongju-enerzai commented on docs/about.md
> +![Visualized Graph](../img/optima_arch.png)
마크다운 프리뷰에서 이미지가 보이지 않는데, 혹시 경로명이 "img/optima_arch.png"가 맞는 게 아닌지 확인 부탁드립니다.

2023-03-08 09:27 UTC, seongju-enerzai commented on docs/about.md
> +- Covers all work to be done in graph level
하단 항목들 내 It들도 지워주셔도 좋을 것 같습니다.

2023-03-08 14:30 UTC, jaeyoon-enerzai commented on docs/about.md
> +    - It extends the scope of AI researchers by supporting complex operations that are not compatible with MHLO, TOSA, and other similar technologies."
fixed

2023-03-08 14:30 UTC, jaeyoon-enerzai commented on docs/about.md
> +    - our first target is to surpass tensorflow(tf-lite), and we will aim to target tvm based compilers
fixed

2023-03-08 14:36 UTC, jaeyoon-enerzai commented on docs/about.md
> +![Visualized Graph](../img/optima_arch.png)
fixed

2023-03-08 14:36 UTC, jaeyoon-enerzai commented on docs/about.md
> +- Covers all work to be done in graph level
fixed

2023-03-13 01:14 UTC, jwkim98 approved these changes

2023-03-13 04:25 UTC, merged