feat : add tutorial docs
ENERZAi/OptimaV2-Docs pull request #5
Opened 2023-02-27 09:30 UTC by jwkim98

Basics tutorial for getting used to Opto language

2023-03-03 05:35 UTC, seongju-enerzai requested changes
about, basics, Chapter 1~2에서 사소한 부분을 포함해 수정되어야 할 부분 코멘트 드립니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +Here is an example designed to help your understanding
문장 끝에 온점('.')이 누락 되었습니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +In this example, we declared 'a' with '3'. and remember, 'let' expression has to return some value. To do so, the expression 'a' in the next line accomplishes the purpose.
'3' 뒤의 문장 부호와 and의 대소문자 표기를 잘 통일해야 할 것 같습니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +Moreover, for 'let b = 2', expression 'a + b' is responsible for returning. At the end, if you follow the recursive structure, the result of 'a + b'(which is 5 here) is the value to be returned.
'a+b' (which is 5 here)과 같이 괄호 앞에 공백이 포함 되어야 합니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +<nex expreession>
expreession -> expression으로 수정해야 합니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +In this case, output of the init expression will be ignored, and let expression will not define any symbol
문장 끝에 온점('.')이 누락 되었습니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +__tuple__ is sequence of values of possibily different types
-> "Tuple is a sequence of values of same or possibly different types."와 같이 변경하면 어떨까요?

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +__List__ is sequence of values of same time
-> List is a sequence of values of the same type.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +#### Using the list or tuple
본 항목 내에 온점이 누락된 부분들이 다소 있어 확인 부탁드립니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +We can Slice list or tuple and get subset of it using [<begin index>:<end index>]. end index must be greater or equal than begin index, and range of begin and end index should be between (0, len(list
- Slice -> slice
- end index -> End index

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +let slicedList = listExample[1:] // returns [2, 3, 5]
[2, 3, 5] -> [2,3,5] (다른 부분과 표기 방식 통일)

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +let slicedList = listExample[0:2] // returns [1, 2]
[1, 2] -> [1,2] (다른 부분과 표기 방식 통일)

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +In opto, we can cast between number typee using 'cast' function. Here is an simple example
- typee -> type
- Here is an simple example -> Here is a simple example.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +There are no restrictions in casting unless we are casting between number types. Casting between any type other than number types are not allowed.
맥락 상 number type 간의 casting만 자유롭다는 것 같아 unless -> when과 같이 수정해야 할 것 같습니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +1. If value is positive, we round down to nearest integer that is less or equal than given value.
That is, 이후의 1. 2. 항목이 개행 되지 않아 가독성이 떨어지는 것 같습니다.
별도 개행을 하거나, 1. -> 1) 등으로 수정하면 어떨까요?

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +2. If value is negative, we round up to nearest integer that is greater or equal than given value.
예를 들어 -1.7과 같이 [-1.5, -2) 범위 내에 있는 수의 경우 -2로 rounding이 되는데, 같거나 더 큰 수로 round 한다는 본 내용에 이 경우에도 잘 부합하는 건지 모르겠습니다.

2023-03-03 05:35 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +In C++, this rule can be implemented as follows (where 'result' means casted output and 'value' means input floating point value)
문장 끝에 온점('.')이 누락 되었습니다.

2023-03-03 06:27 UTC, jwkim98 commented on docs/kernel/Tutorial/Basics.md
> +      * List of 'dynamic' arguments. Dynamic arguments are evaluated during the inference. Therefore, they cannot be determined in compile time. However, they are evaluated in runtime (during the inf
Fixed

2023-03-03 06:27 UTC, jwkim98 commented on docs/kernel/Tutorial/Basics.md
> +This code snippet describes how you can define and write a 'module'
Fixed

2023-03-03 06:28 UTC, jwkim98 commented on docs/kernel/Tutorial/Basics.md
> +Here, the number 1, 2, and symbol 'a' are all expression. These expressions are composed together, and builds bigger expression such as (1 + 2). Now, they build up again, and end up composing the ful
'expression' is correct (Whole program can be thought as a single expression)

2023-03-03 06:31 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +Don't forget Primary purpose of opto language is to generate suitable runtime code that can execute the layer.
fixed

2023-03-03 06:31 UTC, jwkim98 commented on docs/kernel/about.md
> +    * Opto can generate performance-optimized code with consideration of model hyperparameters and target hardware
fixed

2023-03-03 06:32 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +      * List of 'dynamic' arguments. Dynamic arguments are evaluated during the inference. Therefore, they cannot be determined in compile time. However, they are evaluated in runtime (during the inf
Updated

2023-03-03 06:32 UTC, jwkim98 commented on docs/kernel/Tutorial/Basics.md
> +What you can observe here can be divided into three parts.
Updated

2023-03-03 06:33 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +This code defines a with list of three runtime code blocks as a list, and receives compile time argument 'selection'. According to the value of 'selection', this code will generate runtime code that
fixed

2023-03-03 06:33 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +### Embedding compile time expressions in compile time.
fixed

2023-03-03 06:33 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +The following is result of the above code when 'selection' was '2'. and 'valueToAdd' was '4'
fixed

2023-03-03 06:33 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Basics.md
> +Here, the number 1, 2, and symbol 'a' are all expression. These expressions are composed together, and builds bigger expression such as (1 + 2). Now, they build up again, and end up composing the ful
34번 줄 첫 문장 끝의 "~ and symbol 'a' are all expression." 부분에 관한 내용이었습니다.

2023-03-03 06:34 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +We can put any expression that can be converter into runtime code inside compile time code block. Following still works.
fixed

2023-03-03 06:35 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter1.md
> +Now we multiplied 'valueToAdd' with 4, and returned remainder after dividing by '3'. if 'valueToAdd' was for, this code will add '0', since evaluated value of (4*3)%3 is '0'
fixed (was for -> three )

2023-03-03 06:36 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +Here is an example designed to help your understanding
fixed

2023-03-03 06:36 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +In this example, we declared 'a' with '3'. and remember, 'let' expression has to return some value. To do so, the expression 'a' in the next line accomplishes the purpose.
fixed

2023-03-03 06:37 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +Moreover, for 'let b = 2', expression 'a + b' is responsible for returning. At the end, if you follow the recursive structure, the result of 'a + b'(which is 5 here) is the value to be returned.
fixed

2023-03-03 06:37 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +<nex expreession>
fixed

2023-03-03 06:37 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +In this case, output of the init expression will be ignored, and let expression will not define any symbol
fixed

2023-03-03 06:37 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +__tuple__ is sequence of values of possibily different types
fixed

2023-03-03 06:38 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +__List__ is sequence of values of same time
fixed

2023-03-03 06:39 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +#### Using the list or tuple
fixed

2023-03-03 06:39 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +We can Slice list or tuple and get subset of it using [<begin index>:<end index>]. end index must be greater or equal than begin index, and range of begin and end index should be between (0, len(list
fixed

2023-03-03 06:40 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +let slicedList = listExample[1:] // returns [2, 3, 5]
fixed

2023-03-03 06:40 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +let slicedList = listExample[0:2] // returns [1, 2]
fixed

2023-03-03 06:40 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +In opto, we can cast between number typee using 'cast' function. Here is an simple example
fixed

2023-03-03 06:41 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +There are no restrictions in casting unless we are casting between number types. Casting between any type other than number types are not allowed.
fixed

2023-03-03 06:42 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +1. If value is positive, we round down to nearest integer that is less or equal than given value.
fixed

2023-03-03 06:44 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +2. If value is negative, we round up to nearest integer that is greater or equal than given value.
파이썬에서는 해당 경우 -1 로 round 됩니다. 표현을 조금 바꾸는게 좋겠군요

2023-03-03 06:45 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter2.md
> +In C++, this rule can be implemented as follows (where 'result' means casted output and 'value' means input floating point value)
fixed

2023-03-03 06:48 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +2. If value is negative, we round up to nearest integer that is greater or equal than given value.
전에 의논했던 것과 다르게, 제 로컬 환경에서 파이썬 3.10 버전 기준으로 round(-1.7)의 결과로 -2를 반환하는 걸로 확인됩니다.

2023-03-03 06:54 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter2.md
> +2. If value is negative, we round up to nearest integer that is greater or equal than given value.
int 캐스팅에 관한 설명이었는데 제가 착각하고 있었어서, 별도로 말씀 주신 내용 잘 확인했습니다.

2023-03-03 07:44 UTC, jwkim98 commented on docs/kernel/Tutorial/Basics.md
> +Here, the number 1, 2, and symbol 'a' are all expression. These expressions are composed together, and builds bigger expression such as (1 + 2). Now, they build up again, and end up composing the ful
Will fix

2023-03-03 08:40 UTC, seongju-enerzai reviewed
Chapter 5, 7 제외한 나머지 부분 수정 의견 코멘트 드립니다.
우선 중요한 것 위주로만 수정해 주시면 될 것 같습니다.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/HowToRead.md
> +This tutorial is designed to help you getting used to opto language. This is not a reference page that contains every information of Opto, but is written in human-friendly way to guid you understand
Line 3: guid -> guide

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/HowToRead.md
> +2. **Chapter 2 (Understanding compile-time language features)** explains using basic functionalities in Opto such as let bindings, lists, tuples and type casting
Line 10: 문장 마지막 온점 누락 되었습니다.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter3.md
> +This way, we can defined function 'foo' receiving a and b as a parameter and called function 'foo' with 3 and 4, where 3 is assigned to parameter 'a' and 4 is assigned to parameter 'b'.
Line 29: defined -> define

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter3.md
> +Here, we gave only one parameter to function 'foo' that should receive two parameters. In other languages like python or C++, this would cause error since number of parameters did not match number of
Line 41

- cause error -> cause an error
- since number of -> since the number of
- match number -> match the number
- In above code -> In the above code

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter3.md
> +Therefore, we need to pass parameter 'b' to compute the result. Which was '4' in the above example.
Line 47: the result. Which was -> the result which was

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter3.md
> +We now see how 'a' is converted into given parameter, and b is remaining undetermined. Now, foo_partial is a function that receives 'b' and returns 3 + b + 2.
Line 46: and b is -> and 'b' is

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter3.md
> +While c is defined inside scope of if/else statement, we can still compute the 'foo' because c = <value> is already stored inside the closure 'foo'.
Line 106: "c = <value>"에서 "<value>" 부분이 나타나지 않아 기호를 수정해야 할 것 같습니다.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter3.md
> +This code computes fibonacci sequence. Recursive functions defines its name in its captured environment. This is accomplished by fixed point combinator, used to define recursive functions without usi
Line 128: fixed point combinator -> fixed-point combinator

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter4.md
> +In this page, we introduce if/else statement, exception and print statement
Line 4: 문장 끝에 온점이 누락되었습니다.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter4.md
> +The omitted 'else' block returns 'None' as default. Since None type is compatible with any type, (None type is parent type of any other type in Opto) There is no restriction in return type of if clau
Line 29: There is -> there is

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter4.md
> +We can throw exceptions in opto like following. Note that when exception is thrown, program always terminates intermediately. There is not 'catch' functionality in Opto. Therefore, you should use it
Line 32: There is not -> There is no

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter4.md
> +Since 'except' always terminates program, we don't have to think about type compatibility. Opto language does not type-check return value of except because it will be never returned.
Line 34: it will be never returned. -> it will never be returned.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter4.md
> +print(<expression>))
Line 49: print 구문 맨 뒤의 괄호 하나가 삭제되어야 합니다.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter4.md
> +We can print any value in opto language using print statement including non values, or runtime expressions and runtime type.
Line 51: non values -> non-values

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter6.md
> +In Opto, we provide some helper functions that can be useful for writing kernels. Some of them are builtin inside the language itself, and some of them are interpreted as library function (Which mean
Line 3: (Which means -> (which means

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter6.md
> +# Chapter 6. Helper functions
각 function의 하위 리스트 내용 시작 시 대소문자 표기를 통일하면 좋을 것 같습니다.

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter6.md
> +* **broadcast** (listA : list<'T'>, lsitB : list<'T'>)
Line 53: lsitB -> listB

2023-03-03 08:40 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter6.md
> +    * Each list in 'iterables' should have same length, or it will cause compile time interpreter error
Line 71: 문장 끝 온점이 누락되었습니다.

2023-03-03 08:43 UTC, seongju-enerzai approved these changes

2023-03-03 10:58 UTC, seongju-enerzai reviewed
Chapter 5, 7 관련 수정 사항 코멘트 드립니다.
대부분 사소해서 중요한 것 위주로만 부탁드립니다.

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +We can use iterator variables when we need to use the result of the body expression of for, but please note that number of return values and number of iterator variables should match unless there are
Line 97: 문장 뒤 온점 누락

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +In some cases, we might not know number of required nested for loops. This case frequently happens if we don't know the dimension of the given tensor. Supppose we have to add two tensors one by one,
Line 103: know number of -> know the number of

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +Now this will be converted to following runtime code
Line 125: 문장 뒤 온점 누락

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +Here is the description of each section in rt_for expression
Line 155: 문장 뒤 온점 누락

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +    rt_for(itr variable list: itr range list) [update_value : initial_value, ...]{
Line 157, 161, 162: itr_variable_list, itr_range_list와 같이 표기해 주는 게 좋을 것 같습니다.

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +* itr variable list : list of iteration variables to be used in runtime. Given as list of string. beginning of the list indicates outermost loop.
Line 161: beginning -> Beginning

2023-03-03 10:58 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter5.md
> +The key differences are
Line 171: 끝에 ':' 등 추가

2023-03-06 10:23 UTC, jaeyoon-enerzai commented on docs/kernel/Tutorial/Chapter1.md
> +
이런 중요한 point들은 강조나, 다른 색으로 표시하는 것도 좋겠습니다

2023-03-06 10:32 UTC, jaeyoon-enerzai commented
Will approve when one comment is resolved

2023-03-10 05:15 UTC, jwkim98 commented on docs/kernel/Tutorial/Chapter7.md
> +    if(index == len(broadcastedShape)){
== 로 할 경우에도 index가 알맞게 들어온다면 문제가 없지만 만약을 대비해서 >=로 수정하겠습니다

2023-03-10 08:28 UTC, seongju-enerzai requested changes

2023-03-10 08:28 UTC, seongju-enerzai commented on docs/guide/install.md
>      The `install` script will auto-detect compiler and build dependencies for OptimaV2 Runtime. If you want to force `install` script to use specific compiler, flags in below list can be used.
이 부분부터 Step 7 내용까지 개행이 되지 않은 탓인지 읽기 어려운 것 같습니다.

2023-03-12 07:22 UTC, beom-k commented on docs/guide/install.md
>      | feature          | `install` packages     | `cmake` argument      | note                                                          |
build from source 탭에서만 step 3, step 4 정상작동 됩니다

2023-03-12 07:51 UTC, beom-k commented on docs/kernel/Tutorial/HowToRead.md
> +### Opto API
현재는 괜찮은거 같은데, API 부분은 나중에는 따로 나누어지면 좋을 것 같습니다.

2023-03-12 10:28 UTC, beom-k approved these changes
고생하셨습니다

2023-03-13 01:56 UTC, jaeyoon-enerzai approved these changes
다음 버전에서 static tensor들을 runtime에서 사용하기 위해 let으로 한 번 정의해야하는 부분을 추가하면 좋겠습니다
-> 제 쪽 graph 부분에서 static tensor를 compile argument로 바꾸는 PR을 올린 후에

2023-03-13 05:00 UTC, seongju-enerzai approved these changes

2023-03-13 05:00 UTC, seongju-enerzai commented on docs/kernel/Tutorial/Chapter7.md
> +Let's change shape of input 'a' like following
Line 220: 끝에 ':'를 추가해 주시면 좋을 것 같습니다.

2023-03-13 05:11 UTC, merged